# Generated by Django 4.1 on 2023-03-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asyncc', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set(),
        ),
    ]
